import { existsSync } from 'node:fs';
import type { ExpoConfig, ConfigContext } from 'expo/config';

/**
 * Dynamic Expo config.
 *
 * Replaces the previous `app.json` for two reasons:
 *   1. The Mapbox download token can no longer be hard-coded to `sk.placeholder`
 *      — it now reads from the `MAPBOX_DOWNLOAD_TOKEN` env var at build time.
 *      (Public / in-app Mapbox usage still uses `EXPO_PUBLIC_MAPBOX_TOKEN`.)
 *   2. Supabase / Sentry / analytics keys are injected via `extra` so native
 *      code has them at runtime without baking secrets into source control.
 *
 * Permission arrays are deduplicated — the previous file listed
 * `ACCESS_FINE_LOCATION`, `ACCESS_BACKGROUND_LOCATION` and `remote-notification`
 * twice which produced a build warning on Android.
 */
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'Clyzio',
  slug: 'clyzio',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,
  scheme: 'clyzio',
  splash: {
    image: './assets/splash-icon.png',
    resizeMode: 'contain',
    backgroundColor: '#00565A',
  },
  ios: {
    supportsTablet: false,
    bundleIdentifier: 'com.clyzio.app',
    buildNumber: '6',
    infoPlist: {
      NSLocationWhenInUseUsageDescription:
        'Clyzio uses your location to show your position on the map, plan routes, and match you with nearby commuters.',
      NSLocationAlwaysAndWhenInUseUsageDescription:
        'Clyzio uses your location in the background to track active trips and notify you of nearby carpool matches.',
      // Deprecated key (iOS < 11) — provide an honest string so the value
      // generated by older dep templates is not a placeholder during review.
      NSLocationAlwaysUsageDescription:
        'Clyzio uses your location in the background to track active trips and notify you of nearby carpool matches.',
      NSPhotoLibraryUsageDescription:
        'Clyzio needs access to your photo library to let you choose a profile picture.',
      NSCameraUsageDescription:
        'Clyzio needs camera access to let you take a profile picture.',
      // expo-secure-store can require biometric auth on the Keychain item.
      NSFaceIDUsageDescription:
        'Clyzio uses Face ID to keep your account securely signed in on this device.',
      // 'location' background mode removed (2026-07): the app never requests
      // Always authorization and only watches position in the foreground —
      // an unused background-location mode invites App Store rejection.
      UIBackgroundModes: ['remote-notification'],
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#003D40',
    },
    edgeToEdgeEnabled: true,
    package: 'com.clyzio.app',
    versionCode: 6,
    // FCM wiring — REQUIRED for Android push (carpool requests, match
    // approvals, nudges are all push-driven). The file comes from the
    // Firebase console (project settings → Android app → google-services.json).
    // Local builds: drop it at the repo root (gitignored). EAS builds: upload
    // it as a file-type env var named GOOGLE_SERVICES_JSON
    // (`eas env:create --scope project --name GOOGLE_SERVICES_JSON --type file`).
    // Conditional so prebuild doesn't fail before the file exists.
    ...(process.env.GOOGLE_SERVICES_JSON || existsSync('./google-services.json')
      ? { googleServicesFile: process.env.GOOGLE_SERVICES_JSON ?? './google-services.json' }
      : {}),
    // Minimal, honest permission set (Play pre-launch audit 2026-07):
    // location = map/route/matching, vibrate = haptics. The app has NO audio
    // recording, NO in-app camera capture (avatar comes from the photo
    // library), and NO background location (the only watchPositionAsync runs
    // while the trip screen is foregrounded) — so CAMERA / RECORD_AUDIO /
    // ACCESS_BACKGROUND_LOCATION are stripped below, which also removes the
    // Play Console background-location declaration + demo-video requirement.
    permissions: [
      'android.permission.ACCESS_FINE_LOCATION',
      'android.permission.ACCESS_COARSE_LOCATION',
      'android.permission.VIBRATE',
    ],
    // expo-image-picker's plugin injects CAMERA + RECORD_AUDIO into the
    // manifest for video-capture support we don't use; expo-location can
    // inject background location. Block all three explicitly.
    blockedPermissions: [
      'android.permission.RECORD_AUDIO',
      'android.permission.CAMERA',
      'android.permission.ACCESS_BACKGROUND_LOCATION',
    ],
  },
  web: {
    favicon: './assets/favicon.png',
    bundler: 'metro',
  },
  plugins: [
    'expo-router',
    'expo-font',
    'expo-secure-store',
    'expo-localization',
    [
      '@rnmapbox/maps',
      {
        // Secret, build-time token used to fetch native SDK artefacts.
        // Must NOT be committed — expose via EAS secret `MAPBOX_DOWNLOAD_TOKEN`.
        RNMAPBOX_MAPS_DOWNLOAD_TOKEN:
          process.env.MAPBOX_DOWNLOAD_TOKEN ?? '',
      },
    ],
    [
      'expo-location',
      {
        locationWhenInUsePermission:
          'Clyzio uses your location to show your position on the map, plan routes, and match you with nearby commuters.',
        locationAlwaysAndWhenInUsePermission:
          'Clyzio uses your location in the background to track active trips and notify you of nearby carpool matches.',
        // The app only watches location while the trip screen is foregrounded
        // (Location.watchPositionAsync) — no background tracking, so don't let
        // the plugin inject ACCESS_BACKGROUND_LOCATION (Play-review-sensitive).
        isAndroidBackgroundLocationEnabled: false,
      },
    ],
    [
      'expo-image-picker',
      {
        photosPermission:
          'Clyzio needs access to your photo library to let you choose a profile picture.',
        cameraPermission:
          'Clyzio needs camera access to let you take a profile picture.',
        // Clyzio only picks/captures still images for the avatar — no audio.
        // Suppress NSMicrophoneUsageDescription so Apple doesn't flag an
        // unused permission string on review.
        microphonePermission: false,
      },
    ],
    [
      'expo-notifications',
      {
        icon: './assets/icon.png',
        color: '#00565A',
      },
    ],
  ],
  updates: {
    url: 'https://u.expo.dev/565dc638-6385-4dcf-885d-8abd3f0d9c30',
    fallbackToCacheTimeout: 0,
  },
  runtimeVersion: {
    policy: 'appVersion',
  },
  extra: {
    router: {},
    eas: {
      projectId: '565dc638-6385-4dcf-885d-8abd3f0d9c30',
    },
    privacyPolicyUrl: 'https://clyzio.com/legal/privacy',
    supabaseUrl: process.env.EXPO_PUBLIC_SUPABASE_URL,
    supabaseAnonKey: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY,
    mapboxPublicToken: process.env.EXPO_PUBLIC_MAPBOX_TOKEN,
    sentryDsn: process.env.EXPO_PUBLIC_SENTRY_DSN,
    posthogApiKey: process.env.EXPO_PUBLIC_POSTHOG_API_KEY,
    posthogHost: process.env.EXPO_PUBLIC_POSTHOG_HOST,
  },
  owner: 'laurynas.valiunas',
});
