import { useState } from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Share,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { LinearGradient } from "expo-linear-gradient";
import { ArrowLeft, Download, Copy, CheckCircle } from "lucide-react-native";
import { useManagerStore, TimePeriod } from "../../store/useManagerStore";
import { useToast } from "../../contexts/ToastContext";

const COLORS = {
  primary: "#26C6DA",
  primaryDark: "#00ACC1",
  accent: "#FDD835",
  dark: "#006064",
  background: "#F5FAFA",
  white: "#FFFFFF",
  gray: "#90A4AE",
  grayLight: "#F1F5F9",
  green: "#4CAF50",
};

const PERIODS: Array<{ label: string; value: TimePeriod }> = [
  { label: "This Month", value: "month" },
  { label: "This Quarter", value: "quarter" },
  { label: "This Year", value: "year" },
];

function buildReportText(report: ReturnType<typeof useManagerStore.getState>["sustainabilityReport"]): string {
  if (!report) return "";

  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });

  return `CLYZIO SUSTAINABILITY REPORT
Generated: ${today}
${"=".repeat(50)}

GREEN COMMUTE SCORE: ${report.green_commute_score}/100

EXECUTIVE SUMMARY
${report.executive_summary}

IMPACT EQUIVALENTS
• ${report.co2_equivalent.trees_planted} trees planted
• ${report.co2_equivalent.car_km_avoided} car km avoided
• ${report.co2_equivalent.flights_avoided} flights avoided
• Estimated cost savings: €${report.cost_savings_eur}

KEY INSIGHTS
${report.top_insights.map((i, n) => `${n + 1}. ${i.title}\n   ${i.metric}\n   ${i.description}`).join("\n\n")}

DEPARTMENT RANKINGS
${report.department_rankings.map((d, n) => `${n + 1}. ${d.dept_name}: ${d.co2_saved.toFixed(1)} kg CO2 saved (${d.employee_count} employees)`).join("\n")}

RECOMMENDATIONS
${report.recommendations.map((r, n) => `${n + 1}. [${r.esg_pillar}] ${r.action}\n   Impact: -${r.expected_impact_kg_co2} kg CO2 | Effort: ${r.effort} | Timeframe: ${r.timeframe}`).join("\n\n")}

ESG NARRATIVE
${report.esg_narrative}

${"=".repeat(50)}
Generated by Clyzio — Sustainable Commuting Platform
`;
}

export default function ESGExportScreen() {
  const router = useRouter();
  const { showToast } = useToast();
  const { sustainabilityReport, isLoadingReport, fetchSustainabilityReport } =
    useManagerStore();
  const [selectedPeriod, setSelectedPeriod] = useState<TimePeriod>("month");
  const [copied, setCopied] = useState(false);

  const reportText = buildReportText(sustainabilityReport);

  const handleShare = async () => {
    if (!reportText) return;
    try {
      await Share.share({ message: reportText, title: "Clyzio ESG Report" });
    } catch {
      showToast({ title: 'Error', message: 'Could not share the report.', type: 'error' });
    }
  };

  const handleCopy = async () => {
    // Clipboard is only available via expo-clipboard — fallback to share for now
    try {
      const { default: Clipboard } = await import("expo-clipboard");
      await Clipboard.setStringAsync(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback if expo-clipboard not installed
      await handleShare();
    }
  };

  const handleGenerate = () => {
    fetchSustainabilityReport(selectedPeriod);
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
          <ArrowLeft size={22} color={COLORS.dark} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>ESG Export</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView style={styles.scroll} showsVerticalScrollIndicator={false}>

        {/* Period selector */}
        <View style={styles.periodRow}>
          {PERIODS.map((p) => (
            <TouchableOpacity
              key={p.value}
              style={[
                styles.periodBtn,
                selectedPeriod === p.value && styles.periodBtnActive,
              ]}
              onPress={() => setSelectedPeriod(p.value)}
            >
              <Text
                style={[
                  styles.periodText,
                  selectedPeriod === p.value && styles.periodTextActive,
                ]}
              >
                {p.label}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Generate button */}
        <TouchableOpacity
          style={styles.generateBtn}
          onPress={handleGenerate}
          disabled={isLoadingReport}
        >
          <LinearGradient
            colors={[COLORS.primary, COLORS.primaryDark]}
            style={styles.generateGradient}
          >
            <Text style={styles.generateText}>
              {isLoadingReport ? "Generating…" : "Generate Report"}
            </Text>
          </LinearGradient>
        </TouchableOpacity>

        {/* Report preview */}
        {reportText ? (
          <>
            <View style={styles.previewCard}>
              <Text style={styles.previewLabel}>Report Preview</Text>
              <Text style={styles.previewText} numberOfLines={20}>
                {reportText}
              </Text>
            </View>

            {/* Action buttons */}
            <TouchableOpacity style={styles.actionBtn} onPress={handleShare}>
              <Download size={18} color={COLORS.white} />
              <Text style={styles.actionBtnText}>Share / Export</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[styles.actionBtn, styles.copyBtn]}
              onPress={handleCopy}
            >
              {copied ? (
                <CheckCircle size={18} color={COLORS.green} />
              ) : (
                <Copy size={18} color={COLORS.primary} />
              )}
              <Text style={[styles.actionBtnText, { color: copied ? COLORS.green : COLORS.primary }]}>
                {copied ? "Copied!" : "Copy to Clipboard"}
              </Text>
            </TouchableOpacity>
          </>
        ) : (
          <View style={styles.emptyBox}>
            <Download size={36} color={COLORS.gray} />
            <Text style={styles.emptyText}>
              Select a period and generate your ESG report to export it.
            </Text>
          </View>
        )}

        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    paddingHorizontal: 16, paddingVertical: 12,
  },
  backBtn: {
    width: 40, height: 40, borderRadius: 12, backgroundColor: COLORS.white,
    alignItems: "center", justifyContent: "center",
  },
  headerTitle: { fontSize: 18, fontWeight: "bold", color: COLORS.dark },
  scroll: { flex: 1, paddingHorizontal: 16 },

  periodRow: { flexDirection: "row", gap: 8, marginBottom: 14 },
  periodBtn: {
    flex: 1, paddingVertical: 10, borderRadius: 12,
    backgroundColor: COLORS.white, alignItems: "center",
    borderWidth: 1, borderColor: "transparent",
  },
  periodBtnActive: { backgroundColor: COLORS.primary + "15", borderColor: COLORS.primary },
  periodText: { fontSize: 12, color: COLORS.gray, fontWeight: "600" },
  periodTextActive: { color: COLORS.primary },

  generateBtn: { borderRadius: 14, overflow: "hidden", marginBottom: 16 },
  generateGradient: { alignItems: "center", justifyContent: "center", paddingVertical: 14 },
  generateText: { color: COLORS.white, fontWeight: "bold", fontSize: 15 },

  previewCard: {
    backgroundColor: COLORS.white, borderRadius: 18, padding: 16, marginBottom: 14,
    shadowColor: "#000", shadowOpacity: 0.04, shadowRadius: 8, elevation: 2,
  },
  previewLabel: { fontSize: 13, fontWeight: "600", color: COLORS.gray, marginBottom: 10 },
  previewText: { fontSize: 11, color: COLORS.dark, lineHeight: 17, fontFamily: "monospace" },

  actionBtn: {
    flexDirection: "row", alignItems: "center", justifyContent: "center",
    backgroundColor: COLORS.primary, borderRadius: 14, paddingVertical: 14,
    gap: 8, marginBottom: 10,
  },
  copyBtn: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.primary + "40" },
  actionBtnText: { fontSize: 15, fontWeight: "bold", color: COLORS.white },

  emptyBox: {
    alignItems: "center", paddingVertical: 60, gap: 12,
  },
  emptyText: {
    fontSize: 14, color: COLORS.gray, textAlign: "center", paddingHorizontal: 24,
  },
});
